### PR TITLE
fixes an issue introduced by #25

### PR DESCRIPTION
**Pull request by majormoses**
Signed-off-by: Ben Abrams <me@benabrams.it>

## Pull Request Checklist

#25 

#### General

- [x] Update Changelog following the conventions laid out on [Our CHANGELOG Guidelines](https://github.com/sensu-plugins/community/blob/master/HOW_WE_CHANGELOG.md)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [x] RuboCop passes

- [x] Existing tests pass

#### Purpose
Fix issue introduced in #25 

#### Known Compatibility Issues
None

### CODE REVIEW

**Comment by yuri-zubov** [comment]
@majormoses, it looks good

**Review by yuri-zubov — APPROVED** [review]

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-jenkins/versions/1.6.2

**Comment by majormoses** [comment]
@yuri-zubov apologize again for the mishap I am spread a little thin but that is no excuse.

**Comment by yuri-zubov** [comment]
@majormoses never mind, it happens sometimes ;)

**Pull request merged**
